apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-v2
  template:
    metadata:
      labels:
        app: nginx-v2
    spec:
      containers:
      - name: nginx
        image: nginx:c9d1c9d-1691140278
        ports:
        - containerPort: 80
