name: building image
run-name: ${{ github.head_ref }} 
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - run: docker build -t flask:${{ github.head_ref }} -f docker/Dockerfile