name: building image
# run-name: Building -${{ github.head_ref }} by @${{ github.actor }}
on: 
  push:
    branches: [ "main" ]
jobs:
  build-image:
    runs-on: local-system
    steps:
      - run: echo ${{ secrets.MESSAGE }}
      - run: echo -e "GITHUB_ref:${{github.ref}}\nGITHUB_API_URL:${{github.api_url}}\nGITHUB_REF_NAME:${{github.ref_name}}\nGITHUB_ACTOR:${{github.actor}}\nGITHUB_SHA:${{github.sha}}\nGITHUB_HEAD_REF:${{ github.head_ref }}"
      - run: echo ${{ github }}
      - name: Checkout Git
        uses: actions/checkout@v2
        with:
          ref: main
          repository: abhishekchauhan98/flask-app.git
      - name: Building flask app image.
        run: |
          DOCKER_IMAGE_TAG=`echo ${{github.sha}} | cut -c 1-8`
          ls
          docker build -t flask:$DOCKER_IMAGE_TAG -f docker/Dockerfile .