name: building image
run-name: ${{ github.head_ref }} 
on: 
  push:
    branches: [ "main" ]
jobs:
  build-image:
    runs-on: local-system
    steps:
      - run: echo ${{ secrets.MESSAGE }}
      - run: echo -e "GITHUB_ref:${{github.ref}}\nGITHUB_API_URL:${{github.api_url}}\nGITHUB_REF_NAME:${{github.ref_name}}\nGITHUB_ACTOR:${{github.actor}}\nGITHUB_SHA:${{github.sha}}"
      - run: docker build -t flask:${{github.sha}} -f docker/Dockerfile