name: building image
run-name: ${{ github.head_ref }} 
on: 
  push:
    branches: [ "main" ]
jobs:
  build-image:
    runs-on: local-system
    steps:
      - run: echo ${{ secrets.MESSAGE }}
      - run: docker build -t flask:${{github.ref}} -f docker/Dockerfile